[COORDINATOR]
C_PRI = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
C_PUB = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
CON_ADD = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
NUM_VALIDATORS = 5
NUM_PARITIONS = 5
PATH = "./diabetics_data/train.csv"
TARGET = "OUTCOME"
UNIFORM = true
VARIENCE = 50
ZETA = 2
GENISIS_MODEL_CID = "QmXMWqNBH2JGZLU7ArFgF4aJmSiQ5kaJ8mjNV19xRWRPqa"

[VALIDATOR]
BASE = 44601
CON_ADD = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
MAX_ROUNDS = 5
MIN_CLIENTS = 3
N_CLASSES = 2
N_FEATURES = 30
SAVE_PART = true
TARGET = "OUTCOME"
UNIFORM = true
VARIANCE = 10
V_PRI = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
V_PUB = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

[VALIDATOR_UTIL]
K = 3
ALPHA = 3
BETA = 4

[SETUP]
NUM_VALIDATORS = 8
MIN_CLIENTS = 3
PORT_NUM = 44600

[EXPERIMENT]
A_TYPE = "MODEL"
FLIP_NUM = 0
PROPORTION = 6
MALICIOUS = [ 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,]
